// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0NXo5nfP4A-IVMaFIfz7XxKsxFgv2GDA',
    appId: '1:302616700045:web:0e46cd6d1db44833a5eec4',
    messagingSenderId: '302616700045',
    projectId: 'e-books-ada97',
    authDomain: 'e-books-ada97.firebaseapp.com',
    storageBucket: 'e-books-ada97.appspot.com',
    measurementId: 'G-FTJ4W3E75N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6urZHAnuHTYrKDzxEMiX56tlZDWRhDQY',
    appId: '1:302616700045:android:d91bd6585e4c9822a5eec4',
    messagingSenderId: '302616700045',
    projectId: 'e-books-ada97',
    storageBucket: 'e-books-ada97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3SM0GJTz5Qj-vLXB03glcrLD5ygLh8sg',
    appId: '1:302616700045:ios:2d435ac5189429d2a5eec4',
    messagingSenderId: '302616700045',
    projectId: 'e-books-ada97',
    storageBucket: 'e-books-ada97.appspot.com',
    iosBundleId: 'com.example.ebookTask',
  );
}
